### ISSUE TITLE
Bot not recognising any command

### ISSUE THREAD

**Issue by michaelclark09** [Adamo-O/Theme-Song-Discord-Bot#1]
Two people have managed to set a theme song, since then the bot is not recognising any commands

The bot will still join a channel and play music for the two people that have set it

Have tried removing the integration and re-adding

**Comment by Adamo-O** [comment]
> Two people have managed to set a theme song, since then the bot is not recognising any commands
> 
> The bot will still join a channel and play music for the two people that have set it
> 
> Have tried removing the integration and re-adding

Hey,  I'll check this out soon. Sorry about that!

**Comment by michaelclark09** [comment]
Awesome, thank you!

**Comment by Adamo-O** [comment]
@michaelclark09 The issue should be resolved now, there was a change in the Discord intents, stopping it from reading messages.
Let me know if it's working on your end too, and if it is please close the issue, thanks!

**Comment by michaelclark09** [comment]
Sorry for the late reply - this has now been resolved! Thank you
